### ISSUE TITLE
Migrations in worm.toml

### ISSUE THREAD

**Issue by chuck-flowers** [chuck-flowers/worm#10]
Currently a user of worm has to define migrations for their database in code. Support for defining them in the **worm.toml** file should be added. When the CLI is developed, logic for automatically generating migrations based on the code should be added.

# Example

The following Rust record would require the following migration in the **worm.toml** file

**users.rs**
```rust
use worm::records::HasPrimaryKey;
use worm::records::Record;

#[derive(HasPrimaryKey, Record)]
struct User {
  id: i32,
  name: String
}
```

**worm.toml**
```toml
[contexts.default]
connection-string = ":memory:"
dialect = "worm::dialects::StandardSqlDialect"
executor = "worm_sqlite::SqliteDialect"

[[contexts.default.migrations]]
  description = "Add User table"
  [[contexts.default.migrations.actions]]
    type = "AddTable"
    name = "User"
    [[contexts.default.migrations.actions.columns]]
      name = "id"
      type = "i32"
      constraints = ["NotNull", "PrimaryKey"]
    [[contexts.default.migrations.actions.columns]]
      name = "name"
      type = "String"
      constraints = ["NotNull"]
```
